<?php
/**
 * Comprehensive legal glossary for the built-in AI assistant (English).
 * Educational definitions — Mauritian law context where relevant.
 *
 * @return array<string, string>
 */
function ai_legal_glossary_en(): array
{
    return [
        // —— Sources & systems of law ——
        'constitution' => 'The supreme law of the State. All other laws must conform to it. In Mauritius, the Constitution protects fundamental rights and organises government institutions.',
        'act / statute / law' => 'Primary legislation passed by Parliament (the National Assembly). Mauritian Acts are commonly published in English.',
        'subsidiary legislation / regulations' => 'Rules made under authority of an Act (regulations, orders, rules, notices) by the executive.',
        'case law / jurisprudence' => 'Body of judicial decisions used to interpret and apply the law, especially important in common-law areas.',
        'precedent / stare decisis' => 'Principle that courts should follow earlier decisions in similar cases; binding in common-law tradition.',
        'common law' => 'Legal tradition based on judicial decisions and equity, influential in Mauritian procedure and several substantive areas.',
        'civil law (tradition)' => 'Codified Romanist tradition (strong French influence on Mauritian private law, e.g. Civil Code).',
        'equity' => 'Body of fairness principles from English law that supplement strict legal rules.',
        'custom / customary law' => 'Practice recognised as law only where compatible with written legislation.',
        'international law' => 'Rules governing relations between States; treaties may be received into domestic law.',
        'private international law / conflict of laws' => 'Rules determining which country’s law and courts apply to cross-border disputes.',
        'rule of law' => 'Principle that all persons and institutions are subject to publicly made laws applied by independent courts.',
        'ultra vires' => 'Beyond legal power or authority; an act done without lawful competence.',
        'statutory interpretation' => 'Process of construing the meaning and scope of legislation.',

        // —— Branches of law ——
        'civil law (subject)' => 'Branch governing private relations: contracts, property, family, and civil liability.',
        'criminal law' => 'Branch defining offences against the State/society and their penalties.',
        'commercial law' => 'Rules governing trade, business transactions, and commercial instruments.',
        'company law / corporate law' => 'Rules on formation, governance, and winding up of companies (Companies Act 2001 in Mauritius).',
        'employment / labour law' => 'Rules on employment contracts, wages, termination, and workplace rights (Employment Rights Act 2008).',
        'administrative law' => 'Rules governing public bodies and judicial review of administrative action.',
        'constitutional law' => 'Law relating to the Constitution, fundamental rights, and State institutions.',
        'family law' => 'Law of marriage, divorce, parentage, custody, and maintenance.',
        'property law / land law' => 'Rules on ownership, transfer, registration, and security over immovable property.',
        'tax law' => 'Rules on assessment and collection of taxes (Income Tax Act, VAT Act, etc.).',
        'environmental law' => 'Rules on pollution control, environmental impact, and natural resources.',
        'intellectual property law' => 'Law protecting patents, trade marks, copyright, and designs.',
        'banking / financial law' => 'Regulation of banks, securities, and financial services.',
        'insolvency law' => 'Rules on bankruptcy, liquidation, and creditor priority (Insolvency Act 2009).',
        'consumer law' => 'Protection of consumers against unfair trade practices.',
        'competition / antitrust law' => 'Rules preventing anti-competitive agreements and abuse of market power.',
        'data protection / privacy law' => 'Rules on processing personal data (Data Protection Act 2017 in Mauritius).',
        'immigration law' => 'Rules on entry, residence, and removal of non-citizens.',
        'maritime / admiralty law' => 'Law relating to ships, cargo, and maritime accidents.',

        // —— Courts & procedure ——
        'court / tribunal' => 'Institution with authority to adjudicate disputes and impose legal consequences.',
        'supreme court' => 'Superior court of Mauritius with appellate and constitutional jurisdiction.',
        'intermediate court' => 'Mauritian court handling mid-level civil and criminal matters.',
        'district court' => 'Court of first instance for lower-value civil claims and minor offences.',
        'industrial court' => 'Specialist tribunal for employment and labour disputes in Mauritius.',
        'jurisdiction' => 'Legal authority of a court to hear a matter (subject, territorial, or hierarchical).',
        'competence / competency' => 'Power of a court or authority to decide a particular matter.',
        'original jurisdiction' => 'Authority to hear a case at first instance.',
        'appellate jurisdiction' => 'Authority to review decisions of lower courts.',
        'judicial review' => 'Court supervision of lawfulness of administrative decisions.',
        'plaintiff / claimant' => 'Party who initiates a civil claim.',
        'defendant / respondent' => 'Party against whom a claim or charge is brought.',
        'appellant' => 'Party who appeals a decision.',
        'litigant' => 'Any party to court proceedings.',
        'prosecution' => 'State or authority bringing criminal charges; also the process of doing so.',
        'summons' => 'Document commencing or requiring attendance in court proceedings.',
        'writ' => 'Formal written court order commanding or authorising an act.',
        'pleading' => 'Formal written statement of a party’s case (claim, defence, reply).',
        'affidavit' => 'Written statement sworn or affirmed before an authorised officer.',
        'discovery / disclosure' => 'Pre-trial exchange of documents and information between parties.',
        'interrogatories' => 'Written questions one party must answer under oath in civil proceedings.',
        'injunction / interdict' => 'Court order requiring or forbidding specific conduct, sometimes urgently (interim).',
        'interim / interlocutory order' => 'Temporary order pending final resolution of a case.',
        'stay of proceedings' => 'Suspension of court action for a specified reason.',
        'adjournment' => 'Postponement of a hearing to a later date.',
        'in camera' => 'In private; hearings closed to the public.',
        'ex parte' => 'Proceedings in the absence of the other party (often for urgent relief).',
        'lis pendens' => 'Pending lawsuit; also a doctrine affecting transfer of disputed property.',
        'cause of action' => 'Set of facts giving rise to a legal right to sue.',
        'limitation / prescription' => 'Time bar after which legal action may no longer be brought (Limitation Act 1969).',
        'locus standi' => 'Standing; a party’s sufficient interest to bring proceedings.',
        'milestone / calendar (procedural)' => 'Court timetable setting dates for steps in litigation.',
        'default judgment' => 'Judgment entered when a defendant fails to respond or appear.',
        'summary judgment' => 'Judgment without full trial where no real dispute exists on facts or law.',
        'consent order' => 'Court order made with agreement of the parties.',
        'consent decree' => 'Binding court-approved settlement of a case.',
        'settlement' => 'Agreement resolving a dispute without trial or after proceedings begin.',
        'alternative dispute resolution / ADR' => 'Non-court methods such as mediation, arbitration, and conciliation.',
        'mediation' => 'Neutral facilitator helps parties reach voluntary settlement.',
        'arbitration' => 'Private dispute resolution where an arbitrator’s award may be binding.',
        'conciliation' => 'Third party assists parties to settle, often in labour disputes.',
        'without prejudice' => 'Communication that cannot be used as admission in court if negotiations fail.',
        'subpoena' => 'Order compelling a witness to attend or produce documents.',
        'contempt of court' => 'Disobedience or disrespect warranting court sanction.',

        // —— People & roles ——
        'judge / magistrate' => 'Judicial officer who presides over courts and decides cases.',
        'registrar' => 'Court official responsible for records, filings, and administrative judicial functions.',
        'attorney / lawyer / counsel' => 'Legal professional qualified to advise and represent clients.',
        'barrister' => 'Counsel specialising in courtroom advocacy (where the split profession exists).',
        'solicitor' => 'Lawyer handling client matters, documentation, and litigation preparation.',
        'notary (civil law)' => 'Public officer authenticating acts and documents in civil-law tradition.',
        'bailiff / usher' => 'Officer serving court documents and maintaining order.',
        'director of public prosecutions / DPP' => 'Head of public criminal prosecutions.',
        'expert witness' => 'Person with specialised knowledge giving opinion evidence.',
        'lay witness' => 'Person testifying to facts they perceived.',
        'amicus curiae' => 'Friend of the court; independent adviser on legal issues.',
        'fiduciary' => 'Person bound to act in utmost good faith for another’s benefit (trustee, director).',
        'trustee' => 'Person holding property for the benefit of beneficiaries.',
        'executor / executrix' => 'Person appointed to administer a deceased person’s estate.',
        'administrator' => 'Person appointed to manage an estate when no valid will exists.',
        'guardian' => 'Person legally responsible for a minor or incapacitated person.',
        'curator' => 'Person appointed to manage affairs of someone unable to do so.',

        // —— Criminal law ——
        'crime / offence' => 'Act or omission prohibited by law and punishable by the State.',
        'felony (historical/common law)' => 'Serious crime; terminology varies; Mauritius uses statutory offence categories.',
        'misdemeanour (historical/common law)' => 'Less serious offence; modern statutes define classes of offences.',
        'actus reus' => 'Guilty act — the physical element of a crime.',
        'mens rea' => 'Guilty mind — intention, knowledge, or recklessness required for many offences.',
        'strict liability' => 'Liability without proof of fault for certain regulatory offences.',
        'attempt' => 'Intentional steps towards committing an offence that falls short of completion.',
        'conspiracy' => 'Agreement between persons to commit an unlawful act.',
        'aiding and abetting' => 'Assisting or encouraging another to commit an offence.',
        'accessory' => 'Person who helps before or after a crime.',
        'principal offender' => 'Person who actually commits the offence.',
        'arrest' => 'Deprivation of liberty by lawful authority on suspicion of an offence.',
        'bail' => 'Release from custody pending trial on conditions.',
        'remand' => 'Detention or adjournment pending further proceedings.',
        'charge / indictment' => 'Formal accusation of a criminal offence.',
        'arraignment' => 'Formal reading of charges and plea before a court.',
        'plea' => 'Defendant’s formal response to a charge (guilty, not guilty, etc.).',
        'prosecution evidence' => 'Evidence presented to prove the charge beyond reasonable doubt.',
        'defence case' => 'Evidence and arguments presented by the accused.',
        'beyond reasonable doubt' => 'Standard of proof required for criminal conviction.',
        'reasonable suspicion' => 'Lower threshold justifying arrest or search in many contexts.',
        'self-defence' => 'Use of reasonable force to protect oneself or others from unlawful attack.',
        'duress' => 'Coercion by threats; may be a defence to certain crimes.',
        'insanity / mental disorder defence' => 'Defence where accused lacked capacity to understand wrongfulness.',
        'intoxication' => 'May affect mens rea depending on offence and voluntariness.',
        'alibi' => 'Evidence that accused was elsewhere when offence occurred.',
        'murder' => 'Unlawful killing with intent (Criminal Code — severe penalties including life imprisonment).',
        'culpable homicide / manslaughter' => 'Unlawful killing without murder-level intent.',
        'assault' => 'Intentional or reckless causing of apprehension of immediate unlawful force.',
        'battery' => 'Unlawful application of force to another person.',
        'grievous bodily harm / GBH' => 'Serious physical injury; aggravated offence.',
        'theft / larceny' => 'Dishonest appropriation of property belonging to another.',
        'robbery' => 'Theft involving force or threat of force.',
        'burglary / breaking and entering' => 'Unlawful entry with intent to commit an offence.',
        'fraud / false pretences' => 'Deception to obtain property or advantage dishonestly.',
        'forgery' => 'False making or alteration of document with intent to defraud.',
        'bribery / corruption' => 'Offering or receiving improper advantage in breach of duty.',
        'money laundering' => 'Processing criminal proceeds to disguise their origin (FIAML Act in Mauritius).',
        'perjury' => 'Deliberately lying under oath in judicial proceedings.',
        'perverting the course of justice' => 'Interfering with administration of justice.',
        'sedition (where applicable)' => 'Conduct tending to disturb public order or authority (subject to constitutional limits).',
        'sentence' => 'Punishment imposed after conviction (fine, imprisonment, community service, etc.).',
        'probation' => 'Supervised release instead of or after custodial sentence.',
        'parole' => 'Conditional early release from imprisonment.',
        'fine' => 'Monetary penalty imposed for an offence.',
        'community service order' => 'Sentence requiring unpaid work for the community.',
        'death penalty (historical/constitutional context)' => 'Mauritius abolished the death penalty; Constitution restricts reinstatement.',
        'habeas corpus' => 'Remedy challenging unlawful detention.',
        'extradition' => 'Surrender of accused or convicted person to another State.',
        'double jeopardy' => 'Protection against being tried twice for the same offence (Constitution).',
        'search warrant' => 'Judicial authorisation to search premises or seize evidence.',
        'caution (police)' => 'Formal warning given on arrest; rights to silence and legal counsel.',

        // —— Evidence ——
        'evidence' => 'Material presented in court to prove or disprove facts.',
        'burden of proof / onus of proof' => 'Duty on a party to prove disputed facts.',
        'standard of proof' => 'Degree of certainty required (beyond reasonable doubt in criminal; balance of probabilities in civil).',
        'balance of probabilities' => 'Civil standard: more likely than not.',
        'prima facie case' => 'Evidence sufficient to establish a case unless rebutted.',
        'admissibility' => 'Whether evidence may be considered by the court.',
        'hearsay' => 'Out-of-court statement offered for truth of its contents; often restricted.',
        'direct evidence' => 'Evidence based on witness’s own perception.',
        'circumstantial evidence' => 'Evidence from which facts may be inferred.',
        'documentary evidence' => 'Evidence in written or recorded form.',
        'real evidence' => 'Physical object produced in court.',
        'expert evidence' => 'Opinion evidence from qualified specialist.',
        'corroboration' => 'Independent evidence supporting a witness’s account.',
        'cross-examination' => 'Questioning of opposing party’s witness.',
        'examination-in-chief' => 'Questioning of one’s own witness.',
        're-examination' => 'Further questioning after cross-examination on new matters.',
        'privilege (evidence)' => 'Right to withhold certain communications (legal professional privilege, etc.).',
        'legal professional privilege' => 'Confidentiality of lawyer-client communications for legal advice/litigation.',
        'public interest immunity' => 'Withholding documents whose disclosure harms the public interest.',
        'spoliation' => 'Destruction or alteration of evidence.',
        'presumption' => 'Rule treating a fact as true unless disproved.',
        'rebuttable presumption' => 'Presumption that may be overturned by contrary evidence.',
        'res ipsa loquitur' => 'Doctrine where accident type implies negligence without direct proof.',

        // —— Contracts & obligations ——
        'contract' => 'Agreement creating legally enforceable obligations (Civil Code Art. 1134 tradition).',
        'offer' => 'Proposal capable of acceptance forming a contract.',
        'acceptance' => 'Unqualified agreement to an offer.',
        'consideration (common law)' => 'Something of value exchanged; less central in pure civil-law contracts but relevant in hybrid system.',
        'capacity' => 'Legal ability to enter binding obligations (age, mental state).',
        'consent' => 'Free and informed agreement; vitiated by error, fraud, or duress.',
        'mistake / error' => 'Misunderstanding that may void or alter consent.',
        'misrepresentation' => 'False statement inducing contract; may allow rescission or damages.',
        'duress (contract)' => 'Illegitimate pressure vitiating consent.',
        'undue influence' => 'Abuse of power undermining free consent.',
        'unconscionability' => 'Grossly unfair agreement that courts may refuse to enforce.',
        'terms / conditions' => 'Provisions defining parties’ rights and duties.',
        'express terms' => 'Terms explicitly agreed.',
        'implied terms' => 'Terms read into contract by law or custom.',
        'condition (contractual)' => 'Essential term whose breach may terminate the contract.',
        'warranty' => 'Lesser term giving rise to damages but not necessarily termination.',
        'innominate term' => 'Term whose breach consequences depend on seriousness.',
        'breach of contract' => 'Failure to perform without lawful excuse (Civil Code Art. 1147).',
        'anticipatory breach' => 'Clear indication that a party will not perform when due.',
        'fundamental breach' => 'Breach going to root of contract permitting termination.',
        'repudiation' => 'Renunciation of contractual obligations.',
        'rescission' => 'Cancellation putting parties back in pre-contract position where possible.',
        'termination' => 'Ending contract for breach, frustration, or agreement.',
        'frustration' => 'Contract becomes impossible or radically different through no fault of parties.',
        'force majeure' => 'Superior force event excusing performance (if contract or law provides).',
        'specific performance' => 'Court order requiring performance of contractual obligation.',
        'quantum meruit' => 'Reasonable value of work done when no agreed price applies.',
        'liquidated damages' => 'Pre-agreed sum payable on breach (must not be penal).',
        'penalty clause' => 'Punitive sum unenforceable if disproportionate to legitimate interest.',
        'novation' => 'Replacement of contract or party by new agreement.',
        'assignment' => 'Transfer of contractual rights to a third party.',
        'delegation' => 'Transfer of performance duties (where permitted).',
        'third-party beneficiary' => 'Person intended to benefit from a contract between others.',
        'privity of contract' => 'General rule that only parties to contract may sue on it.',
        'parol evidence rule' => 'Restriction on using prior statements to vary written contract (common-law influence).',
        'pacta sunt servanda' => 'Agreements lawfully made must be kept.',
        'good faith' => 'Duty of honesty and fairness in negotiation and performance.',
        'void contract' => 'Contract with no legal effect from the outset.',
        'voidable contract' => 'Contract valid until set aside by affected party.',
        'unilateral contract' => 'Acceptance by conduct of offer open to all.',
        'bilateral contract' => 'Exchange of mutual promises.',
        'gratuitous contract' => 'Contract for no consideration/benefit (donation).',
        'standard form contract' => 'Pre-drafted terms offered on take-it-or-leave-it basis.',
        'exemption clause / limitation clause' => 'Term excluding or limiting liability.',
        'indemnity clause' => 'Promise to compensate for specified loss.',
        'confidentiality clause / NDA' => 'Obligation not to disclose information.',
        'non-compete clause' => 'Restriction on competing activity (must be reasonable).',
        'non-solicitation clause' => 'Restriction on poaching clients or staff.',
        'restrictive covenant' => 'Contractual restriction on use of property or conduct.',
        'restraint of trade' => 'Agreement restricting commercial freedom; enforceable only if reasonable.',

        // —— Tort / civil liability ——
        'tort / delict' => 'Civil wrong (other than breach of contract) giving rise to damages.',
        'civil liability' => 'Duty to repair harm caused to another.',
        'negligence' => 'Failure to take reasonable care causing foreseeable harm.',
        'duty of care' => 'Legal obligation to avoid acts or omissions likely to harm others.',
        'standard of care' => 'Level of caution expected of a reasonable person in the circumstances.',
        'causation' => 'Link between conduct and harm (factual and legal cause).',
        'proximate cause / remoteness' => 'Harm sufficiently connected to wrong to be compensable.',
        'contributory negligence' => 'Claimant’s own fault reducing recoverable damages.',
        'vicarious liability' => 'Liability of employer/principal for acts of employee/agent.',
        'occupiers liability' => 'Duty owed by property occupier to visitors (Occupiers Liability Act 1985).',
        'nuisance' => 'Unlawful interference with use or enjoyment of land or rights.',
        'trespass' => 'Unlawful direct interference with person, land, or goods.',
        'defamation' => 'Publication of false statement harming reputation (libel written, slander spoken).',
        'libel' => 'Defamation in permanent form (writing, broadcast).',
        'slander' => 'Defamation in transient form (speech).',
        'absolute privilege' => 'Complete immunity from defamation suit (e.g. parliamentary speech).',
        'qualified privilege' => 'Defence where statement made without malice in protected context.',
        'fair comment' => 'Defence for honest opinion on matter of public interest.',
        'malicious falsehood' => 'False statement causing financial loss without defamation.',
        'passing off' => 'Misrepresenting goods/services as those of another.',
        'privacy / invasion of privacy' => 'Unauthorised intrusion into private life or data.',
        'unfair dismissal' => 'Termination without valid reason or fair procedure (Employment Rights Act 2008, ss. 45–49).',
        'wrongful dismissal' => 'Breach of contract in ending employment.',
        'constructive dismissal' => 'Employer conduct forcing employee to resign treated as dismissal.',
        'redundancy / retrenchment' => 'Dismissal for operational reasons with prescribed procedure.',
        'damages' => 'Monetary compensation for loss or injury.',
        'compensatory damages' => 'Damages to put claimant in position as if wrong had not occurred.',
        'aggravated damages' => 'Additional damages for humiliation or injury to feelings.',
        'exemplary / punitive damages' => 'Damages to punish and deter outrageous conduct.',
        'nominal damages' => 'Token sum where right violated but no substantial loss.',
        'injunction (tort context)' => 'Order stopping continuing or imminent wrongful act.',

        // —— Property & security ——
        'property / ownership' => 'Right to use, enjoy, and dispose of a thing within legal limits.',
        'immovable property / real property' => 'Land and permanent structures attached to it.',
        'movable property / chattel' => 'Property other than land (goods, vehicles, etc.).',
        'title' => 'Legal ownership or right to property, especially land.',
        'deed / acte' => 'Written instrument transferring or evidencing property rights.',
        'conveyancing' => 'Legal process of transferring property ownership.',
        'registration / transcription' => 'Recording title or charges on official register for publicity.',
        'lease / tenancy' => 'Grant of possession for a term in return for rent.',
        'lessor / landlord' => 'Owner granting lease.',
        'lessee / tenant' => 'Person holding property under lease.',
        'easement / servitude' => 'Right over another’s land (right of way, drainage, etc.).',
        'mortgage / hypothec' => 'Security interest over property for repayment of debt.',
        'charge' => 'Security over property or assets without transfer of possession.',
        'pledge / nantissement' => 'Security where possession of goods is given to creditor.',
        'lien' => 'Right to retain goods until a debt is paid.',
        'fixture' => 'Item attached to land becoming part of immovable property.',
        'adverse possession / prescription acquisitive' => 'Acquisition of title by long possession (where law allows).',
        'partition' => 'Division of co-owned property among co-owners.',
        'co-ownership / indivision' => 'Ownership of property by two or more persons together.',
        'trust (property)' => 'Property held by trustee for beneficiaries.',
        'will / testament' => 'Document disposing of property on death.',
        'codicil' => 'Supplement or amendment to a will.',
        'intestacy' => 'Death without valid will; estate distributed by law.',
        'legacy / bequest' => 'Gift of property in a will.',
        'devise' => 'Gift of immovable property in a will.',
        'probate' => 'Court certification of valid will and appointment of executor.',
        'letters of administration' => 'Court appointment to administer intestate estate.',
        'estate' => 'Property and liabilities left by deceased person.',
        'donation / gift' => 'Gratuitous transfer of property inter vivos.',
        'sale' => 'Contract transferring ownership for price.',
        'exchange' => 'Contract swapping ownership of things.',
        'loan (mutuum / commodatum)' => 'Transfer of use or ownership of thing subject to return.',

        // —— Company & commercial ——
        'company / corporation' => 'Legal person separate from shareholders (Companies Act 2001).',
        'incorporation' => 'Process of registering a company with legal personality.',
        'memorandum / constitution (company)' => 'Document defining company structure and powers.',
        'share / action' => 'Unit of ownership in a company.',
        'shareholder / member' => 'Owner of shares in a company.',
        'director' => 'Person managing company affairs with statutory duties.',
        'board of directors' => 'Governing body of a company.',
        'officer (company)' => 'Director, secretary, or senior manager with legal duties.',
        'corporate veil' => 'Separate legal personality shielding shareholders from personal liability.',
        'piercing the corporate veil' => 'Courts ignore separate personality in fraud or abuse cases.',
        'debenture' => 'Long-term secured or unsecured company debt instrument.',
        'dividend' => 'Distribution of profits to shareholders.',
        'prospectus' => 'Document inviting public investment with required disclosures.',
        'insider trading' => 'Trading securities using non-public price-sensitive information.',
        'winding up / liquidation' => 'Process of closing company, paying debts, distributing surplus.',
        'receiver' => 'Appointee managing company assets for secured creditor.',
        'administration' => 'Insolvency procedure aiming to rescue or realise business.',
        'bankruptcy (personal)' => 'Insolvency procedure for individuals unable to pay debts.',
        'creditor' => 'Person owed a debt or obligation.',
        'debtor' => 'Person who owes a debt or obligation.',
        'secured creditor' => 'Creditor with security over assets.',
        'unsecured creditor' => 'Creditor without security; paid after secured creditors.',
        'guarantee / suretyship / caution' => 'Promise to answer for another’s debt if they default.',
        'joint venture' => 'Commercial collaboration without necessarily forming one company.',
        'partnership' => 'Business carried on by two or more persons sharing profits and liability.',
        'sole proprietorship' => 'Business owned by one person without separate legal personality.',
        'franchise' => 'Licence to operate business using franchisor’s brand and system.',
        'letter of credit' => 'Bank undertaking to pay on presentation of compliant documents.',
        'bill of exchange' => 'Written order to pay a sum at a date or on demand.',
        'promissory note' => 'Written promise to pay a sum.',
        'cheque' => 'Bill of exchange drawn on a bank payable on demand.',
        'insurable interest' => 'Legal interest required to validly insure property or life.',
        'indemnity (insurance)' => 'Contract where insurer compensates for specified loss.',

        // —— Family ——
        'marriage' => 'Legally recognised union creating rights and duties between spouses.',
        'civil marriage' => 'Marriage solemnised before civil authority.',
        'religious marriage' => 'Marriage under religious rites; civil registration may be required.',
        'prenuptial / antenuptial agreement' => 'Contract before marriage regulating property on divorce or death.',
        'matrimonial regime' => 'System governing property between spouses (community, separation, etc.).',
        'community of property' => 'Regime where spouses share ownership of assets acquired during marriage.',
        'separation of property' => 'Regime where spouses retain separate estates.',
        'divorce' => 'Legal dissolution of marriage.',
        'judicial separation' => 'Court order living apart without dissolving marriage.',
        'maintenance / alimony / pension alimentaire' => 'Financial support for spouse or former spouse.',
        'child maintenance' => 'Financial support for children by parent or guardian.',
        'custody / garde' => 'Care and control of a child.',
        'access / visitation / droit de visite' => 'Non-custodial parent’s time with child.',
        'parental authority / parental responsibility' => 'Rights and duties regarding child’s welfare and property.',
        'legitimacy / filiation' => 'Legal parent-child relationship.',
        'adoption' => 'Legal process creating parent-child relationship.',
        'guardianship (family)' => 'Legal care of minor without parental authority.',
        'domestic violence' => 'Abuse within household; protection orders available (Protection from Domestic Violence Act).',

        // —— Constitutional & administrative ——
        'fundamental rights / human rights' => 'Constitutional protections (life, liberty, expression, equality, etc.).',
        'separation of powers' => 'Division of legislative, executive, and judicial functions.',
        'parliament / national assembly' => 'Legislative body passing Acts in Mauritius.',
        'delegated legislation' => 'Subsidiary rules made under powers granted by Parliament.',
        'judicial independence' => 'Courts free from improper executive or legislative control.',
        'natural justice / due process' => 'Fair hearing and impartial decision-maker (audi alteram partem, nemo judex).',
        'audi alteram partem' => 'Hear the other side — rule against deciding without hearing affected party.',
        'nemo judex in causa sua' => 'No one should be judge in their own cause.',
        'legitimate expectation' => 'Administrative fairness protecting expectations from prior conduct.',
        'proportionality' => 'Action must not exceed what is necessary to achieve lawful aim.',
        'certiorari' => 'Order quashing unlawful decision for excess of jurisdiction or error.',
        'mandamus' => 'Order compelling public body to perform a duty.',
        'prohibition' => 'Order preventing inferior court from exceeding jurisdiction.',
        'quashing order' => 'Modern term for setting aside unlawful administrative decision.',
        'public officer' => 'Person holding office or performing public functions.',
        'misfeasance in public office' => 'Public officer abusing power causing harm.',
        'ombudsman (where established)' => 'Independent investigator of maladministration.',

        // —— Tax & finance ——
        'tax / taxation' => 'Compulsory levy by State on income, transactions, or property.',
        'income tax' => 'Tax on income of persons and companies (Income Tax Act 1995).',
        'value added tax / VAT' => 'Consumption tax on supply of goods and services.',
        'withholding tax' => 'Tax deducted at source from payments.',
        'customs duty' => 'Tax on imported goods.',
        'stamp duty' => 'Tax on documents or transactions (transfers, agreements).',
        'assessment' => 'Official determination of tax liability.',
        'tax return' => 'Declaration of income and tax due filed by taxpayer.',
        'tax evasion' => 'Illegal non-payment or underpayment of tax.',
        'tax avoidance' => 'Lawful minimisation of tax; may be challenged if abusive.',
        'capital gains' => 'Profit on disposal of capital assets; tax treatment varies by statute.',
        'allowable deduction' => 'Expense reducing taxable income under tax law.',

        // —— IP & IT ——
        'copyright' => 'Exclusive rights over original literary, artistic, and musical works.',
        'trade mark / trademark' => 'Sign distinguishing goods or services of one undertaking.',
        'patent' => 'Exclusive monopoly over invention for limited period.',
        'industrial design' => 'Protection of appearance of product.',
        'trade secret' => 'Confidential business information protected from misuse.',
        'licence (IP)' => 'Permission to use intellectual property on agreed terms.',
        'infringement (IP)' => 'Unauthorised use of protected intellectual property.',
        'personal data' => 'Information relating to identified or identifiable person.',
        'data controller' => 'Person determining purposes and means of processing personal data.',
        'data processor' => 'Person processing data on controller’s instructions.',
        'consent (data protection)' => 'Freely given, specific agreement to processing where required.',

        // —— Latin maxims (common in law) ——
        'bona fide / bona fides' => 'In good faith.',
        'mala fide / mala fides' => 'In bad faith.',
        'ex parte' => 'On behalf of one party only.',
        'inter alia' => 'Among other things.',
        'inter vivos' => 'Between living persons (during lifetime).',
        'in vitro / in situ (legal usage)' => 'In context: in place / in original position (in situ for property).',
        'ipso facto' => 'By that very fact.',
        'mutatis mutandis' => 'With necessary changes being made.',
        'per se' => 'By itself; inherently.',
        'pro rata' => 'In proportion.',
        'quid pro quo' => 'Something for something; exchange.',
        'sine die' => 'Without fixed date (adjourned indefinitely).',
        'sub judice' => 'Under judicial consideration; publication may be restricted.',
        'sui generis' => 'Unique; of its own kind.',
        'de facto / de jure' => 'In fact / by law.',
        'corpus delicti' => 'Body of the crime; facts proving offence was committed.',
        'ex turpi causa non oritur actio' => 'No action arises from a dishonourable cause.',
        'ignorantia juris non excusat' => 'Ignorance of law is no excuse.',
    ];
}

/**
 * @return array<string, string>
 */
function ai_legal_glossary_fr(): array
{
    return [
        // —— Sources et systèmes ——
        'constitution' => 'Loi fondamentale suprême de l’État ; toute autre norme doit y être conforme.',
        'loi / acte / statute' => 'Législation primaire adoptée par le Parlement (National Assembly).',
        'règlement / législation subsidiaire' => 'Normes prises sous l’autorité d’une loi (règlements, ordres, avis).',
        'jurisprudence' => 'Ensemble des décisions des tribunaux guidant l’interprétation du droit.',
        'précédent / stare decisis' => 'Décision antérieure invoquée ou obligatoire dans des affaires similaires.',
        'common law' => 'Tradition juridique anglaise fondée sur la jurisprudence et l’equity.',
        'droit civil (tradition)' => 'Tradition codifiée d’inspiration romano-française (Code civil à Maurice).',
        'equity' => 'Principes d’équité complétant le droit strict.',
        'droit international' => 'Règles régissant les relations entre États et organisations internationales.',
        'droit international privé' => 'Règles déterminant la loi et le tribunal compétents pour les litiges transfrontaliers.',
        'État de droit / rule of law' => 'Primauté du droit et contrôle par des tribunaux indépendants.',
        'ultra vires' => 'Au-delà des pouvoirs légaux.',
        'interprétation des lois' => 'Détermination du sens et de la portée d’un texte législatif.',

        // —— Branches du droit ——
        'droit civil' => 'Rapports entre personnes privées : contrats, biens, famille, responsabilité.',
        'droit pénal' => 'Infractions et peines.',
        'droit commercial' => 'Commerce, affaires et instruments de crédit.',
        'droit des sociétés' => 'Constitution, gouvernance et dissolution des sociétés (Companies Act 2001).',
        'droit du travail' => 'Contrat de travail, salaires, licenciement (Employment Rights Act 2008).',
        'droit administratif' => 'Action de l’administration et recours pour excès de pouvoir.',
        'droit constitutionnel' => 'Constitution, droits fondamentaux et institutions.',
        'droit de la famille' => 'Mariage, divorce, filiation, garde, pension alimentaire.',
        'droit des biens / droit foncier' => 'Propriété, transfert, transcription, sûretés immobilières.',
        'droit fiscal' => 'Impôts et taxes (Income Tax Act, VAT Act, etc.).',
        'droit de l’environnement' => 'Pollution, impact environnemental, ressources naturelles.',
        'propriété intellectuelle' => 'Brevets, marques, droits d’auteur, dessins.',
        'droit bancaire et financier' => 'Régulation des banques et services financiers.',
        'droit de l’insolvabilité' => 'Faillite, liquidation, priorité des créanciers.',
        'droit de la consommation' => 'Protection du consommateur.',
        'droit de la concurrence' => 'Pratiques anticoncurrentielles et abus de position dominante.',
        'protection des données' => 'Traitement des données personnelles (Data Protection Act 2017).',

        // —— Tribunaux et procédure ——
        'tribunal / cour' => 'Institution chargée de trancher les litiges.',
        'cour suprême' => 'Juridiction supérieure mauricienne (appel et contrôle constitutionnel).',
        'cour intermédiaire' => 'Affaires civiles et pénales de importance intermédiaire.',
        'district court' => 'Première instance pour litiges de moindre valeur.',
        'industrial court' => 'Tribunal du travail.',
        'compétence / jurisdiction' => 'Pouvoir d’un tribunal de connaître d’une affaire.',
        'appel' => 'Recours devant une juridiction supérieure.',
        'contrôle judiciaire / judicial review' => 'Contrôle de légalité des actes administratifs.',
        'demandeur / requérant' => 'Partie qui initie l’action.',
        'défendeur / intimé' => 'Partie contre laquelle l’action est dirigée.',
        'assignation / summons' => 'Acte introductif d’instance ou convocation.',
        'conclusions / pleadings' => 'Écritures exposant les prétentions des parties.',
        'affidavit / affidavit' => 'Déclaration écrite sous serment ou affirmation.',
        'injonction / interdit' => 'Ordonnance imposant ou interdisant un comportement.',
        'mesure conservatoire / interim order' => 'Ordonnance provisoire en attendant le fond.',
        'prescription / limitation' => 'Délai au-delà duquel l’action peut être irrecevable.',
        'transaction / settlement' => 'Accord mettant fin au litige.',
        'médiation' => 'Règlement amiable facilité par un tiers neutre.',
        'arbitrage' => 'Mode privé de règlement des différends.',
        'conciliation' => 'Conciliateur aide les parties à un accord.',
        'médiation-arbitrage / ADR' => 'Modes alternatifs de règlement des conflits.',
        'sans préjudice / without prejudice' => 'Communication inutilisable en preuve si la négociation échoue.',
        'contempt / outrage au tribunal' => 'Non-respect ou obstruction à l’égard du tribunal.',

        // —— Personnes et rôles ——
        'juge / magistrat' => 'Officier judiciaire qui décide des litiges.',
        'avocat / barrister / solicitor' => 'Professionnel du droit conseillant et représentant les clients.',
        'notaire' => 'Officier public authentifiant les actes (tradition civiliste).',
        'témoin expert' => 'Personne qualifiée donnant un avis technique.',
        'fiduciaire / trustee' => 'Personne tenue d’agir au mieux de l’intérêt d’autrui.',
        'exécuteur testamentaire' => 'Personne chargée d’exécuter les volontés du défunt.',
        'tuteur / curateur / guardian' => 'Personne protégeant les intérêts d’un mineur ou incapable.',

        // —— Droit pénal ——
        'infraction / crime / offence' => 'Acte ou omission puni par la loi.',
        'actus reus' => 'Élément matériel de l’infraction.',
        'mens rea / intention' => 'Élément moral : intention, connaissance ou imprudence.',
        'responsabilité stricte' => 'Responsabilité sans faute pour certaines infractions réglementaires.',
        'tentative' => 'Commencement d’exécution d’infraction non achevée.',
        'complicité / aiding and abetting' => 'Aide ou encouragement à commettre une infraction.',
        'arrestation' => 'Privation de liberté par autorité légitime.',
        'caution / bail' => 'Mise en liberté provisoire sous conditions.',
        'inculpation / charge' => 'Accusation pénale formelle.',
        'plaidoirie / plea' => 'Réponse de l’accusé à l’inculpation.',
        'doute raisonnable / beyond reasonable doubt' => 'Standard de preuve en matière pénale.',
        'légitime défense / self-defence' => 'Force raisonnable pour repousser une agression.',
        'meurtre / murder' => 'Homicide volontaire avec intention de tuer.',
        'homicide involontaire / manslaughter' => 'Homicide sans intention meurtrière.',
        'vol / theft' => 'Soustraction frauduleuse de biens.',
        'escroquerie / fraud' => 'Tromperie pour obtenir un bien ou un avantage.',
        'corruption / bribery' => 'Avantage indu en violation de devoir.',
        'blanchiment / money laundering' => 'Dissimulation de l’origine criminelle de fonds.',
        'parjure / perjury' => 'Faux témoignage sous serment.',
        'peine / sentence' => 'Sanction infligée après condamnation.',
        'habeas corpus' => 'Recours contre une détention illégale.',
        'extradition' => 'Remise d’une personne à un État étranger.',
        'non bis in idem / double jeopardy' => 'Interdiction d’être jugé deux fois pour les mêmes faits.',

        // —— Preuve ——
        'preuve / evidence' => 'Éléments présentés pour établir les faits.',
        'charge de la preuve / burden of proof' => 'Obligation de prouver les faits allégués.',
        'preuve hors de tout doute raisonnable' => 'Standard pénal.',
        'preuve par preponderance / balance of probabilities' => 'Standard civil : plus probable qu’improbable.',
        'faisceau d’indices presque complet / prima facie' => 'Preuve suffisante sauf réfutation.',
        'admissibilité' => 'Recevabilité d’un élément de preuve.',
        'rumeur / hearsay' => 'Déclaration extrajudiciaire invoquée pour établir sa véracité.',
        'témoignage / witness evidence' => 'Déclaration d’un témoin en justice.',
        'contre-interrogatoire / cross-examination' => 'Interrogatoire de la partie adverse.',
        'secret professionnel / legal privilege' => 'Confidentialité des communications avec l’avocat.',
        'présomption' => 'Règle tenant un fait pour établi jusqu’à preuve contraire.',

        // —— Contrats et obligations ——
        'contrat' => 'Accord de volontés créant des obligations (Code civil, art. 1134).',
        'offre' => 'Proposition capable d’acceptation.',
        'acceptation' => 'Consentement à l’offre.',
        'consentement' => 'Volonté libre et éclairée ; vicié par erreur, dol ou violence.',
        'erreur / mistake' => 'Erreur sur la substance pouvant vicier le consentement.',
        'dol / fraude / misrepresentation' => 'Manœuvre trompeuse provoquant l’engagement.',
        'violence / duress' => 'Contrainte physique ou morale.',
        'lésion / undue influence' => 'Déséquilibre exploité au détriment d’une partie.',
        'clause / terme contractuel' => 'Disposition définissant droits et obligations.',
        'inexécution / breach of contract' => 'Manquement à l’obligation (art. 1147 Code civil).',
        'résiliation / termination' => 'Fin du contrat pour cause ou accord.',
        'résolution / rescission' => 'Annulation remettant les parties en état.',
        'force majeure' => 'Événement imprévisible empêchant l’exécution.',
        'exécution forcée / specific performance' => 'Obligation d’exécuter le contrat.',
        'dommages-intérêts / damages' => 'Réparation pécuniaire du préjudice.',
        'clause pénale / penalty' => 'Indemnité forfaitaire (non abusive).',
        'novation' => 'Remplacement d’obligation ou de débiteur par une nouvelle.',
        'cession / assignment' => 'Transfert d’un droit à un tiers.',
        'bonne foi / good faith' => 'Loyauté dans les négociations et l’exécution.',
        'nullité / void' => 'Acte juridique sans effet.',
        'nullité relative / voidable' => 'Acte annulable à la demande de la partie protégée.',

        // —— Responsabilité civile ——
        'responsabilité civile / civil liability' => 'Devoir de réparer le dommage causé à autrui.',
        'délit civil / tort' => 'Fait illicite causant un préjudice (art. 1382 tradition).',
        'faute / negligence' => 'Manquement au devoir de diligence raisonnable.',
        'causalité' => 'Lien entre la faute et le dommage.',
        'faute de la victime / contributory negligence' => 'Réduction des dommages si victime partiellement responsable.',
        'responsabilité du fait d’autrui / vicarious liability' => 'Responsabilité du commettant pour son préposé.',
        'trouble de voisinage / nuisance' => 'Gêne anormale dans l’usage du fonds voisin.',
        'trouble de jouissance / trespass' => 'Atteinte à la propriété ou à la personne.',
        'diffamation / defamation' => 'Atteinte à l’honneur ou à la réputation.',
        'licenciement abusif / unfair dismissal' => 'Rupture sans motif valable (Employment Rights Act 2008, ss. 45–49).',
        'licenciement déguisé / constructive dismissal' => 'Démission forcée par comportement fautif de l’employeur.',

        // —— Biens et sûretés ——
        'propriété / ownership' => 'Droit de jouir et disposer d’un bien.',
        'meuble / movable property' => 'Bien susceptible de déplacement.',
        'immeuble / immovable property' => 'Fonds de terre et constructions.',
        'bail / lease' => 'Mise à disposition moyennant loyer.',
        'bailleur / lessor' => 'Propriétaire concédant le bail.',
        'locataire / lessee' => 'Preneur du bail.',
        'servitude / easement' => 'Charge imposée sur un fonds au profit d’un autre.',
        'hypothèque / mortgage' => 'Sûreté réelle immobilière garantissant une dette.',
        'nantissement / pledge' => 'Remise d’un bien meuble en garantie.',
        'testament / will' => 'Acte disposant de ses biens pour après le décès.',
        'codicille / codicil' => 'Modification ou ajout au testament.',
        'succession / estate' => 'Transmission du patrimoine du défunt.',
        'intestat / intestacy' => 'Décès sans testament valide.',
        'legs / legacy' => 'Libéralité par testament.',
        'donation' => 'Libéralité entre vifs.',

        // —— Sociétés ——
        'société / company' => 'Personne morale distincte de ses associés.',
        'action / share' => 'Part du capital social.',
        'associé / shareholder' => 'Titulaire d’actions.',
        'administrateur / director' => 'Dirigeant avec devoirs légaux envers la société.',
        'liquidation / winding up' => 'Cessation d’activité et apurement du passif.',
        'créancier / creditor' => 'Personne ayant une créance.',
        'débiteur / debtor' => 'Personne devant une dette.',
        'caution / guarantee' => 'Garant de la dette d’autrui.',
        'faillite / insolvency' => 'Incapacité de payer les dettes exigibles.',

        // —— Famille ——
        'mariage' => 'Union légale entre époux.',
        'contrat de mariage / prenuptial agreement' => 'Convention régissant les biens des époux.',
        'régime matrimonial' => 'Règles de propriété entre époux.',
        'communauté de biens' => 'Propriété commune des acquêts.',
        'séparation de biens' => 'Patrimoines distincts des époux.',
        'divorce' => 'Dissolution du mariage.',
        'pension alimentaire / maintenance' => 'Contribution aux besoins du conjoint ou de l’enfant.',
        'garde / custody' => 'Soins et contrôle de l’enfant.',
        'autorité parentale / parental responsibility' => 'Ensemble de droits et devoirs vis-à-vis de l’enfant.',
        'adoption' => 'Filiation légale créée par adoption.',
        'violence domestique / domestic violence' => 'Violence au sein du foyer ; ordonnances de protection possibles.',

        // —— Constitutionnel et administratif ——
        'droits fondamentaux' => 'Libertés protégées par la Constitution (expression, égalité, etc.).',
        'séparation des pouvoirs' => 'Répartition législatif, exécutif, judiciaire.',
        'équité procédurale / due process' => 'Droit d’être entendu et juge impartial.',
        'excès de pouvoir' => 'Acte administratif illégal annulable par les tribunaux.',

        // —— Fiscal ——
        'impôt sur le revenu / income tax' => 'Impôt sur les revenus des personnes et sociétés.',
        'TVA / VAT' => 'Taxe sur la valeur ajoutée.',
        'déclaration fiscale / tax return' => 'Déclaration des revenus et impôt dû.',
        'évasion fiscale / tax evasion' => 'Fraude fiscale illégale.',
        'optimisation fiscale / tax avoidance' => 'Réduction légale de l’impôt.',

        // —— PI et données ——
        'droit d’auteur / copyright' => 'Droit exclusif sur les œuvres de l’esprit.',
        'marque / trade mark' => 'Signe distinctif de produits ou services.',
        'brevet / patent' => 'Monopole temporaire sur une invention.',
        'données personnelles' => 'Informations se rapportant à une personne identifiée ou identifiable.',

        // —— Maximes latines ——
        'bona fide' => 'De bonne foi.',
        'mala fide' => 'De mauvaise foi.',
        'ex parte' => 'En l’absence d’une partie.',
        'mutatis mutandis' => 'En y apportant les modifications nécessaires.',
        'sine die' => 'Sans date fixe.',
        'sub judice' => 'Sous l’examen du tribunal.',
        'ignorantia juris non excusat' => 'Nul n’est censé ignorer la loi.',
        'nemo judex in causa sua' => 'Nul ne peut être juge et partie.',
        'audi alteram partem' => 'Il faut entendre l’autre partie.',
    ];
}
